apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-dind-pod-777
spec:
  containers:
  - name: ubuntu-dind-container
    image: cruizba/ubuntu-dind:latest
    securityContext:
      privileged: true
    command: ["sh", "-c", "supervisord && tail -f /dev/null" ]